### ISSUE TITLE
Timeout support.

### ISSUE THREAD

**Issue by lovelydinosaur** [encode/requests-async#11]
The adapter class ought to implement timeout support.

Presumably at `open_connection`, and at `reader.read(...)`.

**Comment by mekicha** [comment]
I want to take a go at this @tomchristie

**Comment by mekicha** [comment]
Based on this [answer](https://stackoverflow.com/a/29756841/3865670), we might need to wrap the calls in `asyncio.wait_for`.

But `open_connection` has `ssl_handshake_timeout=None` keyword argument. So my guess is we need to wrap the call only when ssl is not been used.
Please correct me if I'm wrong

**Comment by lovelydinosaur** [comment]
Sounds right!

**Comment by mekicha** [comment]
PR: #19
