### ISSUE TITLE
Support Custom CA Bundle (Self Signed Certs)

### ISSUE THREAD

**Issue by iwoloschin** [encode/requests-async#32]
Looks like support for self signed certs was inadvertently removed in the last day or two.  Opening an issue to track, if no one else gets to it first I can probably make a PR within a couple of days.

**Comment by lovelydinosaur** [comment]
Thanks yeah - I think it got accidentally dropped amidst something else.
A PR here would be very welcome.

**Comment by iwoloschin** [comment]
Closed via #34.
