### ISSUE TITLE
Benefits of ASGISession as a test client?

### ISSUE THREAD

**Issue by florimondmanca** [encode/requests-async#33]
Hey! I just realized through Python Bytes that requests-async (ASGISession in particular) can be used to build an async test client for ASGI apps.

So I’m considering moving to using this instead of Starlette’s (sync) requests-like client.

But this would require a bit more work on the testing side - eg in pytest you’d need to get pytest-asyncio, decorate test cases, etc.

So I’m asking a simple question — what kind of benefits can using this test client bring in terms of testing?

I’ve had issues precisouly with testing multi-client behavior (eg connect to a WebSocket endpoint and make an HTTP request in the meanwhile), most likely because the event loop management that Starlette’s test client does. Would this simplify this kind of use case?

Thanks!

**Comment by lovelydinosaur** [comment]
Yeah, so E.g. if you’re using the test client, and then also interacting with the database then we don’t need to jump through hoops to also provide a sync databases interface.

It’s a shame that pytest has adopted built-in async support. Wonder what it’d take to convince them that it’d be worthwhile to have it directly in the core package.

**Comment by florimondmanca** [comment]
Okay, thanks. Agreed that it would make sense (to me at least) to have built in support for async in pytest. Anyway, I think we can close this. :-)
