### ISSUE TITLE
requests.exceptions.ConnectionError: Multiple exceptions: [Errno 10060]

### ISSUE THREAD

**Issue by stkubr** [encode/requests-async#49]
Hi, sync requests lib works fine, but requests_async breaks. Here is code to reproduce:

```
import asyncio
import requests_async
import requests

def get_sync():
    response = requests.get('https://www.python.org/')
    return response.text

async def get_async():
    response = await requests_async.get('https://www.python.org/')
    return response.text

res1 = get_sync()
print(res1[:20])

res2 = asyncio.get_event_loop().run_until_complete(asyncio.gather(get_async()))
print(res2[:20])
```

python=3.7.1
requests_async=0.5

Error happen in async part, output: 
File "C:/Users/Kubrsta/.PyCharm2019.1/config/scratches/scratch_9.py", line 10, in get_async
    response = await requests_async.get('https://www.python.org/', verify=False)
  File "E:\anaconda3\lib\site-packages\requests_async\api.py", line 11, in get
    return await request("get", url, params=params, **kwargs)
  File "E:\anaconda3\lib\site-packages\requests_async\api.py", line 6, in request
    return await session.request(method=method, url=url, **kwargs)
  File "E:\anaconda3\lib\site-packages\requests_async\sessions.py", line 79, in request
    resp = await self.send(prep, **send_kwargs)
  File "E:\anaconda3\lib\site-packages\requests_async\sessions.py", line 136, in send
    r = await adapter.send(request, **kwargs)
  File "E:\anaconda3\lib\site-packages\requests_async\adapters.py", line 59, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: Multiple exceptions: [Errno 10060] Connect call failed ('151.101.0.223', 443), [Errno 10060] Connect call failed ('151.101.192.223', 443), [Errno 10060] Connect call failed ('151.101.64.223', 443), [Errno 10060] Connect call failed ('151.101.128.223', 443)

Could it be due to the corporate proxy?

**Comment by lovelydinosaur** [comment]
Not able to replicate locally. I'd start by upgrading to 0.6 and double checking.
Totally possible that the connection failure is due to a corporate proxy, yup. See #7
