### ISSUE TITLE
"ConnectionError: [Errno 104] Connection reset by peer" on one particular website

### ISSUE THREAD

**Issue by dvtan** [encode/requests-async#57]
With normal `requests`, it works:

```
import requests

response = requests.get('https://listings.och.uwaterloo.ca/Listings/Details/Show?rentalId=126696')
```

It also works with aiohttp's client.

But using requests_async results in `requests.exceptions.ConnectionError: [Errno 104] Connection reset by peer`:

```
import asyncio
import requests_async as requests

async def client_example():
    response = await requests.get('https://listings.och.uwaterloo.ca/Listings/Details/Show?rentalId=126696')

loop = asyncio.get_event_loop()
loop.run_until_complete(client_example())
```

**Comment by lovelydinosaur** [comment]
Gotcha - looks like it's to do with the SSL config being setup up differently to `requests` and `aiohttp`. (trying `requests.get('https://listings.och.uwaterloo.ca/...', verify=False)` succeeds)

Having a look into it.

**Comment by lovelydinosaur** [comment]
Installing http3 version 0.6.2 will now resolve this.

`pip install -U http3`

**Comment by lovelydinosaur** [comment]
Thanks for the report!
