### ISSUE TITLE
SSL Verification

### ISSUE THREAD

**Issue by lovelydinosaur** [encode/requests-async#6]
At the moment we're setting no_verify on any SSL requests: https://github.com/encode/requests-async/blob/master/requests_async/adapters.py

`requests` *doesn't* do this, and *does* verify certificates by default.

If you remove the `no_verify` (eg. switch it to `ssl=True` or `ssl = ssl.create_default_context()`) then you'lll get an SSL error with `requests-async`, but not with `requests`.

* Where does requests load the ssl context?
* How can we make sure we're doing the same.

**Comment by mohi7solanki** [comment]
I tried to reproduce the `SSLError` by passing `ssl=True and ssl = ssl.create_default_context()` but it is working, Also it seems like `requests` load the ssl certificate from `certifi` https://github.com/kennethreitz/requests/blob/c501ec986daa4961cd9dee370b5d45ff2e524b37/requests/utils.py#L39

**Comment by lovelydinosaur** [comment]
Gotcha. So, requests attaches the SSL info to the connection here: https://github.com/kennethreitz/requests/blob/master/requests/adapters.py#L416

We'll want something equivalent, except that we should build an SSL context, which we'll use here:

https://github.com/encode/requests-async/blob/master/requests_async/adapters.py#L37
