### ISSUE TITLE
Proxy support

### ISSUE THREAD

**Issue by lovelydinosaur** [encode/requests-async#7]
I'd assume this is probably currently broken, but haven't looked into it yet.

Questions:

* Can anyone confirm if it is currently broken?
* Where does the error occur if so?
* What API in requests do we need to be honoring?
* Where does requests handle proxy connections?

**Comment by oldani** [comment]
I will check this out.

**Comment by blueyed** [comment]
It does not work currently.
It gets passed into `requests_async.adapters.send`, but is not used there.

It looks like passing in a `sock` with a configured proxy (`sock.set_proxy`) to `create_connection` might be a solution.

**Comment by cmeadows** [comment]
Now with the updated `httpcore` version, is this on the docket to be added?

**Comment by lovelydinosaur** [comment]
In due course yup.

**Comment by cmeadows** [comment]
Great! I’m not too terribly familiar with the codebase of `httpcore` or `requests` but more than happy to contribute if needed!

**Comment by lovelydinosaur** [comment]
Closing this one off, in favour of https://github.com/encode/http3/issues/36, since the work will actually be within `http3`.
